Sample_Ntn/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get 'static_pages/home'
  get '/help', to: 'static_pages#help', as: 'helf'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  devise_for :users,
             controllers: {
              #  :omniauth_callbacks => "users/omniauth_callbacks",
               omniauth_callbacks: "users/omniauth_callbacks",
               sessions: "users/sessions",
               registrations: "users/registrations"
             }
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
end

Sample_Ntn/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
            <div class="alert alert-danger">
                The form contains <%= pluralize(object.errors.count, "error") %>.
            </div>
            <ul>
                 <% object.errors.full_messages.each do |msg| %>
                 <li><%= msg %></li>
            <% end %>
            </ul>
    </div>
<% end %>

Sample_Ntn/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
        <%= render @feed_items %>
    </ol>
   <%= will_paginate @feed_items,params: { controller: :static_pages, action: :home } %>
<% end %>

Sample_Ntn/app/views/shared/_footer.html.erb
<footer class="footer">
<small>
The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
</small>
<nav>
<ul>
l>
<li><%= link_to "About",about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="https://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

Sample_Ntn/app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
    <div class="navbar-header">
<button type="button" class="navbar-toggle collapsed"
data-toggle="collapse"
data-target="#bs-example-navbar-collapse-1"
aria-expanded="false">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<ul class="nav navbar-nav navbar-right collapse navbar-collapse"
id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help",helf_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Users",users_path %></li>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings",edit_user_path(current_user) %></li>
            <li class="divider"></li> 
            <li><%= button_to "Log out", logout_path, method: :delete %></li>
  
        <% else %>
      <li><%= link_to "Log in", login_path %></li>
        <% end %>
    </ul>
    </ul>
    </nav>
    </div>
</header>

Sample_Ntn/app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
        <div class="field">
           <%= f.text_area :content, placeholder: "Compose new micropost..." %>
        </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
    <span class="image">
         <%= f.file_field :image , accept: "image/jpeg,image/gif,image/png"%>
    </span>
<% end %>
<script type="text/javascript">
    $("#micropost_image").bind("change", function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
         if (size_in_megabytes > 5) {
            alert("Maximum file size is 5MB. Please choose a smaller file.");
            $("#micropost_image").val("");
            }
    });
</script>

Sample_Ntn/app/views/shared/_stats.html.erb
<% @user ||= current_user %>
  <div class="stats">
    <a href="<%= following_user_path(@user) %>">
      <strong id="following" class="stat">
        <%= @user.following.count %>
      </strong>
      following
    </a>
    <a href="<%= followers_user_path(@user) %>">
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
      followers
    </a>
  </div>

Sample_Ntn/app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>