Sample_Ntn/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get 'static_pages/home'
  get '/help', to: 'static_pages#help', as: 'helf'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  devise_for :users,
             controllers: {
              #  :omniauth_callbacks => "users/omniauth_callbacks",
               omniauth_callbacks: "users/omniauth_callbacks",
               sessions: "users/sessions",
               registrations: "users/registrations"
             }
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
end

Sample_Ntn/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:xx
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :microposts, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token, :activation_token, :reset_token
  devise :omniauthable, :database_authenticatable, :recoverable, :registerable,
         :rememberable, :validatable, omniauth_providers: [ :google_oauth2, :facebook]

  before_save :downcase_email
  before_create :create_activation_digest
  before_save { email.downcase } # Dam bao tinh only
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  #    has_secure_password khoong duoc dung lan voi devise

  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # Returns the hash digest of the given string. Trả về thông báo băm của chuỗi đã cho.
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      # user.avatar_url = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
  class << self
    def digest(string)
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create(string, cost:)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  # Ghi nhớ một người dùng trong cơ sở dữ liệu để sử dụng trong các phiên liên tục.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end
  # Returns true if the given token matches the digest.
  ## Trả về true nếu mã thông báo đã cho khớp với thông báo.

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def session_token
    remember_digest || remember
  end
  # Activates an account.
  # Kích hoạt tài khoản.

  # def activate
  #   update_columns(activated: FILL_IN, activated_at: FILL_IN)
  # end
  # Sends activation email.
  # Gửi email kích hoạt.

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  # gui gmail
  # Activates an account.
  # Kích hoạt tài khoản.

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end
  # Sets the password reset attributes.
  # Đặt thuộc tính đặt lại mật khẩu.

  def create_reset_digest
    self.reset_token = User.new_token
    # update_attribute(:reset_digest, User.digest(reset_token))
    # update_attribute(:reset_sent_at, Time.zone.now)
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  # Returns true if a password reset has expired.
  # Trả về true nếu quá trình đặt lại mật khẩu đã hết hạn.

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Defines a proto-feed.
  # See "Following users" for the full implementation.
  def feed
    # Micropost.where("user_id = ?", id)
    # Micropost.where("user_id IN (?) OR user_id = ?", following_ids, id)

    #  following_ids = "SELECT followed_id FROM relationships Nguyen trong Nghia
    #  WHERE follower_id = :user_id"
    #  Micropost.where("user_id IN (:following_ids) OR user_id = :user_id",
    #  following_ids: following_ids, user_id: id)

    part_of_feed = 'relationships.follower_id = :id or microposts.user_id = :id'
    Micropost.left_outer_joins(user: :followers).where(part_of_feed, { id: })
  end

  # Chuong 14
  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  private

  # Converts email to all lower-case.
  ## Chuyển đổi email thành tất cả các chữ thường.

  def downcase_email
    self.email = email.downcase
  end
  # Creates and assigns the activation token and digest.
  # Tạo và chỉ định mã thông báo kích hoạt và thông báo.

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

Sample_Ntn/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

Sample_Ntn/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end
  def google_oauth2
    user = User.from_omniauth(auth)

      if user.present?
        user.activate
        sign_out_all_scopes
        flash[:success] = t "devise.omniauth_callbacks.success", kind: "Google"
        forwarding_url = session[:forwarding_url]
        reset_session
        log_in user

        redirect_to forwarding_url || user
      #  sign_in_and_redirect user, event: :authentication
      else
        flash[:alert] = t "devise.omniauth_callbacks.failure",
          kind: "Google",
          reason: "#{auth.info.email} is not authorized."
        redirect_to new_user_session_path
      end
    end
    #facebook
    def facebook
      user = User.from_omniauth(auth)

        if user.present?
          user.activate
          sign_out_all_scopes
          flash[:success] = t "devise.omniauth_callbacks.success", kind: "facebook"
          forwarding_url = session[:forwarding_url]
          reset_session
          log_in user

          redirect_to forwarding_url || user
        #  sign_in_and_redirect user, event: :authentication
        else
          flash[:alert] = t "devise.omniauth_callbacks.failure",
            kind: "Google",
            reason: "#{auth.info.email} is not authorized."
          redirect_to new_user_session_path
        end
      end

  # protected
  protected

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  private
    def auth
      @auth ||= request.env["omniauth.auth"]
    end
end

Sample_Ntn/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

Sample_Ntn/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

Sample_Ntn/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end
  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

Sample_Ntn/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

Sample_Ntn/app/controllers/users_controller.rb
# frozen_string_literal: true

# Service to download ftp files from the server
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index edit update destroy]
  before_action :correct_user, only: %i[edit update]
  before_action :admin_user, only: :destroy
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    # redirect_to root_url and return unless FILL_IN    ?????????
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # reset_session
      # log_in @user
      # flash[:success] = "Welcome to the Sample App!"
      # redirect_to @user
      # gui gmail

      @user.send_activation_email
      UserMailer.account_activation(@user).deliver_now
      flash[:info] = 'Please check your email to activate your account.'
      redirect_to root_url
    # xxxxxxxx
    # @user.send_activation_email
    # flash[:info] = "Please check your email to activate your account."
    # redirect_to root_url
    # Handle a successful save.
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    # Handle a successful update.
    else
      render 'edit'
    end
  end

  def index
    # @users = User.all.paginate(page: params[:page])
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to users_url
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  # following
  def following
    @title = 'Following'
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # Before filters# Trước bộ lọc
  # Confirms a logged-in user.# Xác nhận người dùng đã đăng nhập.
  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = 'Please log in.'
    redirect_to login_url
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

Sample_Ntn/app/helpers/users_helper.rb
# frozen_string_literal: true

# Service to download ftp files from the server
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

Sample_Ntn/app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
<div><%= hidden_field_tag :followed_id, @user.id %></div>
<%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

Sample_Ntn/app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
        <% if current_user.following?(@user) %>
           <%= render 'unfollow' %>
        <% else %>
          <%= render 'follow' %>
    <% end %>
    </div>
<% end %>

Sample_Ntn/app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

Sample_Ntn/app/views/users/_test.html.erb
<%= form_for "Login",url: omniauth_authorize_path(resource_name, provider),method: :post,data: {turbo: "false"} do |f| %>
      <%= f.submit "Login", type: "image", src: url_for("/assets/btn_google_signin_dark_pressed_web.png") %>
<%= end %>

Sample_Ntn/app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
html: { method: :delete }, remote: true) do |f| %>
<%= f.submit "Unfollow", class: "btn" %>
<% end %>

Sample_Ntn/app/views/users/_user.html.erb
<li>
        <%= link_to user.id, user %>:
        <%= gravatar_for user, size: 50 %>
        <%= link_to user.name, user %> <% if current_user.admin? && !current_user?(user) %>
        | <%= button_to "delete", user, method: :delete,
        data: { confirm: "You sure?" } %>
        <% end %>

</li>

Sample_Ntn/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= form_with(model: @user, local: true) do |f| %>
                    <%= render 'shared/error_messages', object: f.object %>
                    
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>

                    <%= f.label :email %>
                    <%= f.email_field :email, class: 'form-control' %>

                    <%= f.label :password %>
                    <%= f.password_field :password, class: 'form-control' %>
                    <%= f.label :password_confirmation, "Confirmation" %> 
                    <%= f.password_field :password_confirmation, class: 'form-control' %>
                    
                    <%= f.submit "Save changes", class: "btn btn-primary" %>
            <% end %>
            <div class="gravatar_edit">
                <%= gravatar_for @user %>
                <a href="https://gravatar.com/emails">change</a>
            </div>
        </div>
</div>

Sample_Ntn/app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
<%= render @users %>
</ul>
<%= will_paginate @users%>   

Sample_Ntn/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= form_with(model: @user, local: true) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
                <%= f.label :password_confirmation, "Confirmation" %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
                <%= f.submit "Create my account", class: "btn btn-primary" %>

            <% end %>

        </div>








</div>

Sample_Ntn/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section>
  <h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>
  </section>
  <section class="stats">
    <%= render 'shared/stats' %>
  </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

Sample_Ntn/app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
      <div class="user_avatars">
        <% @users.each do |user| %>
        <%= link_to gravatar_for(user, size: 30), user %>
        <% end %>
      </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
    <%= will_paginate %>
    <% end %>
  </div>
</div>